---
title: "Bacterioplankton response to salinity (aka 2015 CSI Dispersal Experiment)"
author: "Alex Stucy, Jo Werba, Mike McCoy, Ariane Peralta"
date: "Last updated on `r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
  fig_caption: true
---

```{r}
rm(list = ls())
setwd("~/GitHub/CSI_Dispersal/analyses")
```

```{r}
#Set Std Err and Conf Int
se <- function(x, ...) {
sd(x, na.rm = TRUE)/sqrt(length(na.omit(x)))
}
ci <- function(x, ...) {
1.96 * sd(x, na.rm = TRUE)
}
```

```{r}
#Set Source R Tools
source("../bin/DiversityFunctions.R")
source("../bin/MothurTools.R")
```

```{r}
#load required packages
require("vegan")
require("dplyr")
require("nlme")
require("reshape2")
require("BiodiversityR")  # Is this needed?
require("ecodist")
require("ggplot2")
require("ade4")
require("png")
```

```{r}
# load design file 
# - this is the real design file
design <- read.csv("../data/CSI_Design_ENV_NoSourceTanks.csv", row.names=1)
head(design)
str(design)
```

# Microbial Data
```{r}
# load design file 
# - this is the design file associated with microbes and needs to get subset w/o mock
design_crobes <- read.csv("../data/design_CSI.csv", row.names=1)
design_crobes <- design_crobes[-c(grep("mock community", design_crobes$CSI_ID)), ]
dim(design_crobes)

# Import OTU data
# Import Raw Data
CSIdata.in <- read.otu("../data/CSI.shared")
dim(CSIdata.in)

# Removing Extra Site in Design site = CSI041
missing <- setdiff(rownames(design_crobes), rownames(CSIdata.in))
design_crobes <- design_crobes[-(which(rownames(design_crobes) == missing)), ]
dim(design_crobes)

design <- design[-(which(rownames(design) == missing)), ]
dim(design) #92,15

# Identify source tanks where Number = 1, 2, 3
temp <- rownames(design_crobes[which(design_crobes$Number %in% c(1, 2, 3)), ])

# Remove sampeles from tank numbers 1, 2, 3
bac.design <- design_crobes[-(which(rownames(design_crobes) %in% temp)), ]
design_crobes2 <- droplevels(bac.design)
dim(design_crobes2)

# Remove source tanks where Number = 1, 2, 3
CSIdata.in2 <- CSIdata.in[-(which(rownames(CSIdata.in) %in% temp)), ]
dim(CSIdata.in2)

# Remove OTUs with less than two occurences across all sites
CSIdat.a <- CSIdata.in2[, which(colSums(CSIdata.in2) >= 2)]
dim(CSIdat.a)

# Rarefy Abundances (min abundance is ___ after removing samples <10000) - need to fix
#aa <- (rowSums(CSIdat.a))
#aa
#CSI.r <- rrarefy(CSIdat.a, 13000)

# removed low abundance samples (CSI101 had 75 reads)
CSIdat.b <- CSIdat.a[which(rowSums(CSIdat.a) >= 13000), ]
dim(CSIdat.b)

# Odd sites in bacterial composition data (CS101) and remove CS041 in design file
odd.sites <- c("CSI101")

CSIdata.in3 <- CSIdat.b[setdiff(rownames(CSIdat.b), odd.sites), ]
design2 <- design[setdiff(rownames(design), odd.sites), ]

all.equal(rownames(design2), rownames(CSIdata.in3))

#set treatments (salinity levels)
treatments1 <- as.factor(design2$Salinity)
levels(treatments1) <- c("0","5","9","13")
treatments2 <- as.factor(design2$Dispersal)
levels(treatments2) <- c("2","3")

date_1 <- as.factor(design2$Date2)

# Make Presence Absence Matrix
CSIdataPA <- (CSIdata.in3 > 0) * 1

# Make Relative Abundence Matrices
CSIdataREL <- CSIdata.in3
for(i in 1:dim(CSIdata.in3)[1]){
  CSIdataREL[i,] <- CSIdata.in3[i,]/sum(CSIdata.in3[i,])
}

```

```{r}
#import taxonomy file - simplified name
CSI.tax1 <- read.tax(taxonomy = "../data/CSI.0.03.cons.taxonomy")
#create tax table .csv and export
write.table(CSI.tax1, file = "tax.csv", sep = ",",
col.names = NA)
```

```{r}
#bind design and bact files
newCSIdata <- cbind(design2,CSIdataREL)

#PERMANOVA
adonis = adonis(newCSIdata[,-c(1:15)] ~ Date2*Dispersal*Salinity, method = "bray", data = newCSIdata, perm=1000)
adonis

capture.output(adonis(newCSIdata[,-c(1:15)] ~ Date2*Dispersal*Salinity, method = "bray", data = newCSIdata, perm=1000), file="disper_sal_permanova1.doc")
```


```{r}
#matrix comparison - Is there a relationship between zooplankton and bacterial community? = YES Mantel r = 0.409, P<0.0001

zoop <- read.csv("../data/zoop_CSI.csv", row.names=1)
str(zoop)
dim(zoop)

#removed low samples
zoop.in <- zoop[,-c(1:6)]
dim(zoop.in)

#remove CSI026
odd.sites <- c("CSI026")
zoop.in2 <- zoop.in[setdiff(rownames(zoop.in), odd.sites), ]
CSIdata.in4 <- CSIdata.in3[setdiff(rownames(CSIdata.in3), odd.sites), ]

# Make Relative Abundence Matrices without CSI026
zoopREL <- zoop.in2
for(i in 1:dim(zoop.in2)[1]){
  zoopREL[i,] <- zoop.in2[i,]/sum(zoop.in2[i,])
}

CSIdataREL2 <- CSIdata.in4
for(i in 1:dim(CSIdata.in4)[1]){
  CSIdataREL2[i,] <- CSIdata.in4[i,]/sum(CSIdata.in4[i,])
}

dist.zoop <- vegdist(zoopREL, method = "bray")
dist.bact <- vegdist(CSIdataREL2, method = "bray")

mantel.rtest(dist.zoop, dist.bact, nrepet = 999)
```

# PCoA
```{r}
sampleREL.dist1 <- vegdist(CSIdataREL, method="bray")
# Principal Coordinates Analysis
CSI_pcoa1 <- cmdscale(sampleREL.dist1, k=3, eig=TRUE, add=FALSE)
  # Classical (Metric) Multidimensional Scaling; returns PCoA coordinates
  # eig=TRUE returns eigenvalues; k = # of dimensions to calculate

explainvar1a <- round(CSI_pcoa1$eig[1] / sum(CSI_pcoa1$eig), 3) * 100
explainvar2a <- round(CSI_pcoa1$eig[2] / sum(CSI_pcoa1$eig), 3) * 100
sum.eiga <- sum(explainvar1a, explainvar2a)

explainvar1a
explainvar2a
```

# PCoA Plot Design
```{r}
head(design2)
all.equal(rownames(design2), rownames(CSIdataREL))

pcoa.groups <- paste(design2$Date2, design2$Salinity, sep = "_")

pcoa.points <- data.frame(CSI_pcoa1$points, group = pcoa.groups)

# Calculate Centroids (mean and SE)
pcoa.L.centroids <- melt(pcoa.points, id="group", measure.vars = c("X1", "X2"))
pcoa.centroids <- acast(pcoa.L.centroids, variable ~ group, mean)
pcoa.centroids.se <- acast(pcoa.L.centroids, variable ~ group, se)
pcoa.centroids.sd <- acast(pcoa.L.centroids, variable ~ group, sd)

# Combine
pcoa.cent.dataframe <- cbind(t(pcoa.centroids), t(pcoa.centroids.se))
colnames(pcoa.cent.dataframe) <- c("V1", "V2", "V1e", "V2e")
pcoa.cent.treats <- rownames(pcoa.cent.dataframe)

pcoa.col <- as.factor(sapply(strsplit(pcoa.cent.treats, "_"), `[`, 2)) # Salinity
pcoa.shape <- as.factor(sapply(strsplit(pcoa.cent.treats, "_"), `[`, 1))  # Date2
```

# Plot (ggplot)
```{r}
df1a <- as.data.frame(pcoa.cent.dataframe)
plot1a <- ggplot(df1a, aes(x=V1, y=V2, colour=pcoa.col, shape = pcoa.shape,
                 group = interaction(pcoa.col, pcoa.shape))) + theme_bw() 
plot1a + theme(panel.grid.major = element_blank(), 
               panel.grid.minor = element_blank(), 
               axis.line = element_line(colour = "black")) + 
theme(panel.background = element_blank()) + 
  geom_point(aes(fill=pcoa.col), colour = "black", size=6, stroke = 0.75) + 
  geom_errorbarh(aes(xmax=V1+V1e, xmin=V1-V1e, height=0.01), colour="black") +    
  geom_errorbar(aes(ymax=V2+V2e, ymin=V2-V2e, width=0.01), colour="black") + 
  scale_colour_manual(labels = c("0","5","9","13"), 
                      values = c("#FFFFFF", "#00FFFF", "#33CCCC", "#0066CC")) + 
  scale_fill_manual(labels = c("0","5","9","13"), 
                    values = c("#FFFFFF", "#00FFFF", "#33CCCC", "#0066CC")) + 
  scale_shape_manual(labels = c("0","18","45"),
                     values = c(22, 21, 24)) +
  coord_cartesian(xlim = c(-0.25, 0.5), ylim = c(-0.35, 0.3)) + 
  theme(axis.title = element_text(size=18), axis.text=element_text(size=14), 
          axis.text.x = element_text(size=14), 
          panel.border = element_rect(colour = "black", size=1.25)) + 
  theme(axis.ticks.length=unit(0.3,"cm")) + 
  xlab("PCoA 1 (21.7%)") + ylab("PCoA 2 (6.6%)") + 
  labs(fill = "Salinity", shape = "Date") +
  guides(fill = guide_legend(override.aes = list(pch=21, size = 4, colour="black")),
         shape = guide_legend(override.aes = list(size = 4, fill="black")))

ggsave("16SrRNA_CSI_Rplot_SalinityDispersal.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=900, limitsize=TRUE)



```


# I pretty much just redid everything below, delete delete 


```{r}
#salinity = color, dispersal = shape; need to graph date x salinity x dispersal

# Organize Data
points1a <- cbind(as.data.frame(CSI_pcoa1$points), treatments1)

# Calculate Centroids (mean and SE)
L.centroids1a <- melt(points1a, id="treatments1", measure.vars = c("V1", "V2"))
centroids1a <- cast(L.centroids1a, variable ~ treatments1, mean)
centroids.se1a <- cast(L.centroids1a, variable ~ treatments1, se)
centroids.sd1a <- cast(L.centroids1a, variable ~ treatments1, sd)

cent.dataframe1a <- t(data.frame(rbind(centroids1a[1,-1], centroids1a[2,-1],
                             centroids.sd1a[1,-1],centroids.sd1a[2,-1])))
colnames(cent.dataframe1a) <- c("V1", "V2", "V1e", "V2e")
cent.treats1a <- rownames(cent.dataframe1a)

#salinity
points1a <- cbind(as.data.frame(CSI_pcoa1$points), treatments1)
L.centroids1a <- melt(points1a, id="treatments1", measure.vars = c("V1", "V2"))
centroids1a <- cast(L.centroids1a, variable ~ treatments1, mean)
centroids.se1a <- cast(L.centroids1a, variable ~ treatments1, se)
centroids.sd1a <- cast(L.centroids1a, variable ~ treatments1, sd)

cent.dataframe1a <- t(data.frame(rbind(centroids1a[1,-1], centroids1a[2,-1],
                             centroids.sd1a[1,-1],centroids.sd1a[2,-1])))
colnames(cent.dataframe1a) <- c("V1", "V2", "V1e", "V2e")
cent.treats1a <- rownames(cent.dataframe1a)

##########################
#dispersal
points2 <- cbind(as.data.frame(CSI_pcoa1$points), treatments2)
L.centroids2 <- melt(points2, id="treatments2", measure.vars = c("V1", "V2"))
centroids2 <- cast(L.centroids2, variable ~ treatments2, mean)
centroids.se2 <- cast(L.centroids2, variable ~ treatments2, se)
centroids.sd2 <- cast(L.centroids2, variable ~ treatments2, sd)

cent.dataframe2 <- t(data.frame(rbind(centroids2[1,-1], centroids2[2,-1],
                             centroids.sd2[1,-1],centroids.sd2[2,-1])))
colnames(cent.dataframe2) <- c("V1", "V2", "V1e", "V2e")
cent.treats2 <- rownames(cent.dataframe2)
```


```{r}
#################################### 
#salinity = color, dispersal = shape - NEED HELP WITH CHANGING SHAPE - graph date x salinity x dispersal
df1a <- as.data.frame(cent.dataframe1a)
plot1a <- ggplot(df1a, aes(x=V1, y=V2, colour=cent.treats1a)) + theme_bw() 
plot1a + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + 
theme(panel.background = element_blank()) + 
  geom_errorbarh(aes(xmax=V1+V1e, xmin=V1-V1e, height=0.01), colour="black") +    
  geom_errorbar(aes(ymax=V2+V2e, ymin=V2-V2e, width=0.01), colour="black") + 
  geom_point(size=5,shape=as.factor(date_1)) +
  scale_colour_manual(labels = c("0","5","9","13"),   values = c("#FFFFCC", "#FFFF00", "#FF9933", "#66CC00")) +
  geom_point(size = 5,colour = "black") + 
  scale_shape_manual(labels = c("2","3"), values = c(1,5)) + 
  
theme(axis.title=element_text(size=18), axis.text=element_text(size=14), axis.text.x   = element_text(size=14), panel.border = element_rect(colour = "black",size=1.25)) + 
  theme(axis.ticks.length=unit(0.3,"cm")) + 
  xlab("PCoA 1 (21.7%)") + ylab("PCoA 2 (6.6%)") + 
  labs(color = "Salinity") +
  guides(colour = guide_legend(override.aes = list(pch=21, size = 4, colour="black",    
  fill=c("#FFFFCC", "#FFFF00", "#FF9933", "#66CC00")))) 

ggsave("16SrRNA_CSI_Rplot_SalinityDisp.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)

#################################### 
#salinity
df1a <- as.data.frame(cent.dataframe1a)
plot1a <- ggplot(df1a, aes(x=V1, y=V2, colour=cent.treats1a)) + theme_bw() 
plot1a + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + 
theme(panel.background = element_blank()) + 
  geom_errorbarh(aes(xmax=V1+V1e, xmin=V1-V1e, height=0.01), colour="black") +    
  geom_errorbar(aes(ymax=V2+V2e, ymin=V2-V2e, width=0.01), colour="black") + 
  geom_point(size=5) +
  scale_colour_manual(labels = c("0","5","9","13"),   values = c("#FFFFCC", "#FFFF00", "#FF9933", "#66CC00")) +
  geom_point(shape=1, size = 5,colour = "black") +
theme(axis.title=element_text(size=18), axis.text=element_text(size=14), axis.text.x   = element_text(size=14), panel.border = element_rect(colour = "black",size=1.25)) + 
  theme(axis.ticks.length=unit(0.3,"cm")) + 
  xlab("PCoA 1 (17.2%)") + ylab("PCoA 2 (7.4%)") + 
  labs(color = "Salinity") +
  guides(colour = guide_legend(override.aes = list(pch=21, size = 4, colour="black",    
  fill=c("#FFFFCC", "#FFFF00", "#FF9933", "#66CC00")))) 

#ggsave("16SrRNA_CSI_Rplot_Salinity.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)

####################################
#dispersal
df2 <- as.data.frame(cent.dataframe2)
plot2 <- ggplot(df2, aes(x=V1, y=V2, colour=cent.treats2)) + theme_bw() 
plot2 + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + 
theme(panel.background = element_blank()) + 
  geom_errorbarh(aes(xmax=V1+V1e, xmin=V1-V1e, height=0.01), colour="black") +    
  geom_errorbar(aes(ymax=V2+V2e, ymin=V2-V2e, width=0.01), colour="black") + 
  geom_point(size=5) +
  scale_colour_manual(labels = c("2","3"),   values = c("#FF9933", "#66CC00")) +
  geom_point(shape=1, size = 5,colour = "black") +
theme(axis.title=element_text(size=18), axis.text=element_text(size=14), axis.text.x = element_text(size=14), panel.border = element_rect(colour = "black",size=1.25)) + 
  theme(axis.ticks.length=unit(0.3,"cm")) + 
  xlab("PCoA 1 (17.2%)") + ylab("PCoA 2 (7.4%)") + 
  labs(color = "Dispersal") +
  guides(colour = guide_legend(override.aes = list(pch=21, size = 4, colour="black",    
  fill=c("#FF9933", "#66CC00")))) 
    
#ggsave("16SrRNA_CSI_Rplot_Dispersal.pdf", plot=last_plot(), device=NULL, path=NULL, scale=1, width=NA, height=NA, dpi=300, limitsize=TRUE)
```

```{r}
#How much bacterial variation is explained by salinity, N, P?
#bind design and bact files
#newCSIdata <- cbind(design2,CSIdataREL) code from PERMANOVA section
# Log Transform Relative Abundances
df <- decostand(CSIdataREL, method="hellinger")
newCSIdata <- cbind(design2,CSIdataREL)

newCSIdata.2 <- na.omit(newCSIdata) #drop missing data NA for salinity
df.bcc <- newCSIdata.2[,-c(1:15)] #bacteria
df.env.bcc <- newCSIdata.2[,c(1:15)] #env
df.nuts <-newCSIdata.2[,c(9:11)] #nutrients

#To test significance salinity on bacterial community section 6.1 partition of variation based on redundancy analysis http://cc.oulu.fi/~jarioksa/opetus/metodi/sessio2.pdf

f <- df.bcc ~ Salinity_real + NH4um + NO3um + PO4um
df.rda <- rda(f, data=df.env.bcc)
anova(df.rda)

mod <- varpart(df.bcc, ~ Salinity_real, df.nuts, data=df.env.bcc)
mod

#How much bacterial variation is explained by decomposition rates? - view into structure-function relationship?
#distance-based redundancy analysis bacterial community ~ decomposition rates for Date2=45 only
newCSIdata.3 <- subset(newCSIdata.2, Date2=="45")

df.bcc <- newCSIdata.3[,-c(1:15)] #bacteria
df.env.bcc <- newCSIdata.3[,c(1:15)] #env
df.decomp <- newCSIdata.3[,c(12:14)] #decomp

f <- df.bcc ~ Maple_dmass + Spartina_dmass + Phrag_dmass
df.rda <- rda(f, data=df.env.bcc)
anova(df.rda)

#Is there a relationship betwen bacterial community composition and decomposition rate? used matrix comparison Mantel test
dist.bcc <- vegdist(df.bcc, method = "bray")
dist.decomp <- vegdist(df.decomp, method = "euclidean")

mantel.rtest(dist.bcc, dist.decomp, nrepet = 999)

```

```{r}
########I did not update this diversity metrics section - AP
```
