---
title: "ODE_Oct1"
author: "Jo"
date: "October 1, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(deSolve)
library(here)
```



```{r state}
state <- c(
  ammonium = 10,
  daph_j = 0,
  daph_a = 20,
  algae  = 20
)

```


```{r getparams}
param <- read.csv(here("RDS_compiled/parameters_no_cerio.csv"))

parameters <- c(
  alpha = 0.2339,    #mg N/(ug chl*day)
  kappa = 0.639,  # 0.2153469,    #mg N
  epsilon =  12,               #ug chl/mgN
  death1 = 2.4,         # 1/day
  fa = median(param$a_feed_m),       # ug chl/(daphniaA*day)
  fj = median(param$j_feed_m),       # ug chl/(daphniaj*day)
  rho = 0.0785709,                    # mg N/ chl
  camm = 1- median(param$amm_param_b),     # 1/day
  xa = median(param$a_exc_m),       # mg N/ (daphniaA*day) ##mmm no bc fit with chl double check param
  xj= median(param$j_exc_m),        # mg N/ (daphniaJ*day) ##mmm no bc fit with chl double check param
  g1 =median(param$growth_a),        # daphniaD/(daphniaJ*day)
  g2=median(param$growth_b),         # ug chl
  #g1 = 1/4.8,
  death2 = 1/median(param$death_b),   # 1/day
  b1 = median(param$fec_a),       # daphniaJ/(daphniaD*day)
  b2 = median(param$fec_b),        # ug chl 
  death3 = 1/median(param$death_b)  # 1/day
)




```



```{r fulleqs}

full_equations <-function(t, state, parameters) {
  with(as.list(c(state, parameters)),{
  
    # ammonium is added from release by both juvenile and adult daphnia  and lost through algal update and nitritfication 
    dammonium <- -(alpha*ammonium)/(kappa+ammonium)*algae + rho*death1*algae - camm*ammonium + daph_a*xa + daph_j*xa/10
    
    
    
    
    
    #juvenile daphia are added by density dependent (large daphnia) birth      
    ddaph_j <- daph_a*(b1*algae)/(b2+algae) - daph_j*death3*10

      
      
    #daphnia adults are added from growth by juveniles and are lost from death
    ddaph_a <- - daph_a*death3 +(g1*algae)/(g2+algae)  #+daph_j*g1 ## wrong...should be growth * daphj?
    
    
    
    # algae is added from growth based on uptake of ammonium 
    dalgae <- (alpha*ammonium)/(kappa+ammonium)*algae*epsilon - death1*algae- daph_a*fa - daph_j*fj
      
    
    
    # return the rate of change
    list(c(dammonium, ddaph_j,ddaph_a,dalgae))
  }) 
}



```




```{r ode1}
out <- ode(y = state, times = seq(0,100,0.1), func = full_equations, parms = parameters)
## out2 <- ode(y = state, times = seq(0,0.4,0.001), func = full_equations, parms = parameters, maxsteps=1e5)
plot(out)
out_med <- ode(y = state, times = seq(0,42,0.1), func = full_equations, parms = parameters)
plot(out_med)
```




Upper bound of predictions
```{r upper}
parameters_upp <- c(
  alpha = 0.5983917,    #mg N/(ug chl*day)
  kappa = 0.2153469,    #mg N
  e =  12,               #ug chl/mgN
  death1 = 1/26,         # 1/day
  fa = quantile(param$a_feed_m, c(0.975), names = F),       # ug chl/(daphniaA*day)
  fj = quantile(param$j_feed_m, c(0.975), names = F),       # ug chl/(daphniaj*day)
  rho = 0.0785709,                    # mg N/ chl
  camm = 1- quantile(param$amm_param_b, c(0.975), names = F),     # 1/day
  xa = quantile(param$a_exc_m, c(0.975), names = F),       # mg N/ (daphniaA*day) 
  xj= quantile(param$j_exc_m, c(0.975), names = F),        # mg N/ (daphniaJ*day) 
  g1 =quantile(param$growth_a, c(0.975), names = F),        # daphniaD/(daphniaJ*day)
  g2=quantile(param$growth_b, c(0.975), names = F),         # ug chl
  death2 = 1/quantile(param$death_b, c(0.975), names = F),   # 1/day
  b1 = quantile(param$fec_a, c(0.975), names = F),       # daphniaJ/(daphniaD*day)
  b2 = quantile(param$fec_b, c(0.975), names = F),        # ug chl 
  death3 = 1/quantile(param$death_b, c(0.975), names = F)  # 1/day
)

out_up <- ode(y = state, times = seq(0,42,0.1), func = full_equations, parms = parameters_upp)
```


Lower bound of predictions

```{r}
parameters_low <- c(
  alpha = 0.5983917,    #mg N/(ug chl*day)
  kappa = 0.2153469,    #mg N
  e =  12,               #ug chl/mgN
  death1 = 1/26,         # 1/day
  fa = quantile(param$a_feed_m, c(0.025), names = F),       # ug chl/(daphniaA*day)
  fj = quantile(param$j_feed_m, c(0.025), names = F),       # ug chl/(daphniaj*day)
  rho = 0.0785709,                    # mg N/ chl
  camm = 1- quantile(param$amm_param_b, c(0.025), names = F),     # 1/day
  xa = quantile(param$a_exc_m, c(0.025), names = F),       # mg N/ (daphniaA*day) 
  xj= quantile(param$j_exc_m, c(0.025), names = F),        # mg N/ (daphniaJ*day) 
  g1 =quantile(param$growth_a, c(0.025), names = F),        # daphniaD/(daphniaJ*day)
  g2=quantile(param$growth_b, c(0.025), names = F),         # ug chl
  death2 = 1/quantile(param$death_b, c(0.025), names = F),   # 1/day
  b1 = quantile(param$fec_a, c(0.025), names = F),       # daphniaJ/(daphniaD*day)
  b2 = quantile(param$fec_b, c(0.025), names = F),        # ug chl 
  death3 = 1/quantile(param$death_b, c(0.025), names = F)  # 1/day
)

out_low <- ode(y = state, times = seq(0,42,0.1), func = full_equations, parms = parameters_low)

```



For graphing

```{r graph ammonium and algae}
pred <- as.data.frame(out_low)
pred$quantile <- "low"
predup <- as.data.frame(out_up)
predup$quantile <- "upper"
predmed <- as.data.frame(out_med)
predmed$quantile <- "med"

source("treatments.R")
source("fix_chl.R")
# the filter remves 3 points at 60 which have to be wrong...all on the same day
dat_daph <- newdat %>% filter(treatment == 3) %>% filter(NH4 < 20)%>%  
   dplyr::select(TankNum, NH4, Chl,Day)
names(dat_daph) <- c("TankNum", "ammonium","algae","time")
amm_g <- ggplot(predmed, aes(time,ammonium)) + geom_line(linetype = "solid") + 
  #geom_line(data= predup, linetype = "dotdash") +
  #geom_line(data=pred, linetype ="dotdash")+
  theme_bw()+ geom_point(data = dat_daph,aes(time,ammonium) )+
  ylab("Ammonium mg/L")+xlab("Days")+
  theme(axis.text.x = element_text(size = 30),
        axis.text.y = element_text(size = 32),
        axis.title.x = element_text(size = 30),
        axis.title.y = element_text(size = 32),
        strip.text = element_text(size = 0),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank()) 


alg_g <- ggplot(predmed, aes(time,algae)) + geom_line(linetype = "solid")+ 
  #geom_line(data= predup, linetype = "dotdash") + geom_line(data=pred, linetype ="dotdash")+
  theme_bw()+ geom_point(data = dat_daph,aes(time,algae) )+
  ylab("Chl a ug/L")+xlab("Days")+
  theme(axis.text.x = element_text(size = 30),
        axis.text.y = element_text(size = 32),
        axis.title.x = element_text(size = 30),
        axis.title.y = element_text(size = 32),
        strip.text = element_text(size = 0),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank()) 

```

```{r graph daphnia}
source("pop_curves.R")
adult <- popA %>% filter(treatment == 3) %>% group_by(TankNum,ExptDay) %>%
  summarize(pop_mean = mean(count)*(mean(Liters)/.01)) %>% dplyr::select(TankNum, ExptDay, pop_mean)
names(adult) <- c("TankNum", "time","daph_a")

juv <- popJ %>% filter(treatment == 3) %>% group_by(TankNum,ExptDay) %>%
  summarize(pop_mean = mean(count)*(mean(Liters)/.01))
names(juv) <- c("TankNum","time","daph_j")

ad_graph <- ggplot(predmed, aes(time,daph_a)) + geom_line(linetype = "solid")+ 
  #geom_line(data= predup, linetype = "dotdash") + geom_line(data=pred, linetype ="dotdash")+
  theme_bw()+ geom_point(data = adult,aes(time,daph_a) )+
  ylab("Adult Daphnia")+xlab("Days")+
  theme(axis.text.x = element_text(size = 30),
        axis.text.y = element_text(size = 32),
        axis.title.x = element_text(size = 30),
        axis.title.y = element_text(size = 32),
        strip.text = element_text(size = 0),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank()) 

juv_graph <- ggplot(predmed, aes(time,daph_j)) + geom_line(linetype = "solid")+ 
  #geom_line(data= predup, linetype = "dotdash") + geom_line(data=pred, linetype ="dotdash")+
  theme_bw()+ geom_point(data = juv,aes(time,daph_j) )+
  ylab("Adult Daphnia")+xlab("Days")+
  theme(axis.text.x = element_text(size = 30),
        axis.text.y = element_text(size = 32),
        axis.title.x = element_text(size = 30),
        axis.title.y = element_text(size = 32),
        strip.text = element_text(size = 0),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.background = element_blank())


```

